# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/leosocy/Desktop/GraduationProject

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/leosocy/Desktop/GraduationProject

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/leosocy/Desktop/GraduationProject/CMakeFiles /home/leosocy/Desktop/GraduationProject/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/leosocy/Desktop/GraduationProject/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

functions/extract_roi/extract_roi.o: functions/extract_roi/extract_roi.cpp.o

.PHONY : functions/extract_roi/extract_roi.o

# target to build an object file
functions/extract_roi/extract_roi.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_roi/extract_roi.cpp.o
.PHONY : functions/extract_roi/extract_roi.cpp.o

functions/extract_roi/extract_roi.i: functions/extract_roi/extract_roi.cpp.i

.PHONY : functions/extract_roi/extract_roi.i

# target to preprocess a source file
functions/extract_roi/extract_roi.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_roi/extract_roi.cpp.i
.PHONY : functions/extract_roi/extract_roi.cpp.i

functions/extract_roi/extract_roi.s: functions/extract_roi/extract_roi.cpp.s

.PHONY : functions/extract_roi/extract_roi.s

# target to generate assembly for a file
functions/extract_roi/extract_roi.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_roi/extract_roi.cpp.s
.PHONY : functions/extract_roi/extract_roi.cpp.s

functions/extract_roi/peak_valley_detect.o: functions/extract_roi/peak_valley_detect.cpp.o

.PHONY : functions/extract_roi/peak_valley_detect.o

# target to build an object file
functions/extract_roi/peak_valley_detect.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_roi/peak_valley_detect.cpp.o
.PHONY : functions/extract_roi/peak_valley_detect.cpp.o

functions/extract_roi/peak_valley_detect.i: functions/extract_roi/peak_valley_detect.cpp.i

.PHONY : functions/extract_roi/peak_valley_detect.i

# target to preprocess a source file
functions/extract_roi/peak_valley_detect.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_roi/peak_valley_detect.cpp.i
.PHONY : functions/extract_roi/peak_valley_detect.cpp.i

functions/extract_roi/peak_valley_detect.s: functions/extract_roi/peak_valley_detect.cpp.s

.PHONY : functions/extract_roi/peak_valley_detect.s

# target to generate assembly for a file
functions/extract_roi/peak_valley_detect.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_roi/peak_valley_detect.cpp.s
.PHONY : functions/extract_roi/peak_valley_detect.cpp.s

functions/pretreatment/adjust_palm.o: functions/pretreatment/adjust_palm.cpp.o

.PHONY : functions/pretreatment/adjust_palm.o

# target to build an object file
functions/pretreatment/adjust_palm.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/pretreatment/adjust_palm.cpp.o
.PHONY : functions/pretreatment/adjust_palm.cpp.o

functions/pretreatment/adjust_palm.i: functions/pretreatment/adjust_palm.cpp.i

.PHONY : functions/pretreatment/adjust_palm.i

# target to preprocess a source file
functions/pretreatment/adjust_palm.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/pretreatment/adjust_palm.cpp.i
.PHONY : functions/pretreatment/adjust_palm.cpp.i

functions/pretreatment/adjust_palm.s: functions/pretreatment/adjust_palm.cpp.s

.PHONY : functions/pretreatment/adjust_palm.s

# target to generate assembly for a file
functions/pretreatment/adjust_palm.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/pretreatment/adjust_palm.cpp.s
.PHONY : functions/pretreatment/adjust_palm.cpp.s

functions/pretreatment/binarization.o: functions/pretreatment/binarization.cpp.o

.PHONY : functions/pretreatment/binarization.o

# target to build an object file
functions/pretreatment/binarization.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/pretreatment/binarization.cpp.o
.PHONY : functions/pretreatment/binarization.cpp.o

functions/pretreatment/binarization.i: functions/pretreatment/binarization.cpp.i

.PHONY : functions/pretreatment/binarization.i

# target to preprocess a source file
functions/pretreatment/binarization.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/pretreatment/binarization.cpp.i
.PHONY : functions/pretreatment/binarization.cpp.i

functions/pretreatment/binarization.s: functions/pretreatment/binarization.cpp.s

.PHONY : functions/pretreatment/binarization.s

# target to generate assembly for a file
functions/pretreatment/binarization.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/pretreatment/binarization.cpp.s
.PHONY : functions/pretreatment/binarization.cpp.s

global/general_function.o: global/general_function.cpp.o

.PHONY : global/general_function.o

# target to build an object file
global/general_function.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/global/general_function.cpp.o
.PHONY : global/general_function.cpp.o

global/general_function.i: global/general_function.cpp.i

.PHONY : global/general_function.i

# target to preprocess a source file
global/general_function.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/global/general_function.cpp.i
.PHONY : global/general_function.cpp.i

global/general_function.s: global/general_function.cpp.s

.PHONY : global/general_function.s

# target to generate assembly for a file
global/general_function.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/global/general_function.cpp.s
.PHONY : global/general_function.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... main"
	@echo "... functions/extract_roi/extract_roi.o"
	@echo "... functions/extract_roi/extract_roi.i"
	@echo "... functions/extract_roi/extract_roi.s"
	@echo "... functions/extract_roi/peak_valley_detect.o"
	@echo "... functions/extract_roi/peak_valley_detect.i"
	@echo "... functions/extract_roi/peak_valley_detect.s"
	@echo "... functions/pretreatment/adjust_palm.o"
	@echo "... functions/pretreatment/adjust_palm.i"
	@echo "... functions/pretreatment/adjust_palm.s"
	@echo "... functions/pretreatment/binarization.o"
	@echo "... functions/pretreatment/binarization.i"
	@echo "... functions/pretreatment/binarization.s"
	@echo "... global/general_function.o"
	@echo "... global/general_function.i"
	@echo "... global/general_function.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

