# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/leosocy/Desktop/GraduationProject

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/leosocy/Desktop/GraduationProject

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/leosocy/Desktop/GraduationProject/CMakeFiles /home/leosocy/Desktop/GraduationProject/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/leosocy/Desktop/GraduationProject/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

functions/PRML/src/PRML.o: functions/PRML/src/PRML.cpp.o

.PHONY : functions/PRML/src/PRML.o

# target to build an object file
functions/PRML/src/PRML.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/PRML/src/PRML.cpp.o
.PHONY : functions/PRML/src/PRML.cpp.o

functions/PRML/src/PRML.i: functions/PRML/src/PRML.cpp.i

.PHONY : functions/PRML/src/PRML.i

# target to preprocess a source file
functions/PRML/src/PRML.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/PRML/src/PRML.cpp.i
.PHONY : functions/PRML/src/PRML.cpp.i

functions/PRML/src/PRML.s: functions/PRML/src/PRML.cpp.s

.PHONY : functions/PRML/src/PRML.s

# target to generate assembly for a file
functions/PRML/src/PRML.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/PRML/src/PRML.cpp.s
.PHONY : functions/PRML/src/PRML.cpp.s

functions/PRML/src/PRMLEDRCC.o: functions/PRML/src/PRMLEDRCC.cpp.o

.PHONY : functions/PRML/src/PRMLEDRCC.o

# target to build an object file
functions/PRML/src/PRMLEDRCC.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/PRML/src/PRMLEDRCC.cpp.o
.PHONY : functions/PRML/src/PRMLEDRCC.cpp.o

functions/PRML/src/PRMLEDRCC.i: functions/PRML/src/PRMLEDRCC.cpp.i

.PHONY : functions/PRML/src/PRMLEDRCC.i

# target to preprocess a source file
functions/PRML/src/PRMLEDRCC.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/PRML/src/PRMLEDRCC.cpp.i
.PHONY : functions/PRML/src/PRMLEDRCC.cpp.i

functions/PRML/src/PRMLEDRCC.s: functions/PRML/src/PRMLEDRCC.cpp.s

.PHONY : functions/PRML/src/PRMLEDRCC.s

# target to generate assembly for a file
functions/PRML/src/PRMLEDRCC.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/PRML/src/PRMLEDRCC.cpp.s
.PHONY : functions/PRML/src/PRMLEDRCC.cpp.s

functions/PRML/src/PRMLKNearest.o: functions/PRML/src/PRMLKNearest.cpp.o

.PHONY : functions/PRML/src/PRMLKNearest.o

# target to build an object file
functions/PRML/src/PRMLKNearest.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/PRML/src/PRMLKNearest.cpp.o
.PHONY : functions/PRML/src/PRMLKNearest.cpp.o

functions/PRML/src/PRMLKNearest.i: functions/PRML/src/PRMLKNearest.cpp.i

.PHONY : functions/PRML/src/PRMLKNearest.i

# target to preprocess a source file
functions/PRML/src/PRMLKNearest.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/PRML/src/PRMLKNearest.cpp.i
.PHONY : functions/PRML/src/PRMLKNearest.cpp.i

functions/PRML/src/PRMLKNearest.s: functions/PRML/src/PRMLKNearest.cpp.s

.PHONY : functions/PRML/src/PRMLKNearest.s

# target to generate assembly for a file
functions/PRML/src/PRMLKNearest.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/PRML/src/PRMLKNearest.cpp.s
.PHONY : functions/PRML/src/PRMLKNearest.cpp.s

functions/PRML/src/PRMLNBayes.o: functions/PRML/src/PRMLNBayes.cpp.o

.PHONY : functions/PRML/src/PRMLNBayes.o

# target to build an object file
functions/PRML/src/PRMLNBayes.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/PRML/src/PRMLNBayes.cpp.o
.PHONY : functions/PRML/src/PRMLNBayes.cpp.o

functions/PRML/src/PRMLNBayes.i: functions/PRML/src/PRMLNBayes.cpp.i

.PHONY : functions/PRML/src/PRMLNBayes.i

# target to preprocess a source file
functions/PRML/src/PRMLNBayes.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/PRML/src/PRMLNBayes.cpp.i
.PHONY : functions/PRML/src/PRMLNBayes.cpp.i

functions/PRML/src/PRMLNBayes.s: functions/PRML/src/PRMLNBayes.cpp.s

.PHONY : functions/PRML/src/PRMLNBayes.s

# target to generate assembly for a file
functions/PRML/src/PRMLNBayes.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/PRML/src/PRMLNBayes.cpp.s
.PHONY : functions/PRML/src/PRMLNBayes.cpp.s

functions/PRML/src/PRMLSVM.o: functions/PRML/src/PRMLSVM.cpp.o

.PHONY : functions/PRML/src/PRMLSVM.o

# target to build an object file
functions/PRML/src/PRMLSVM.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/PRML/src/PRMLSVM.cpp.o
.PHONY : functions/PRML/src/PRMLSVM.cpp.o

functions/PRML/src/PRMLSVM.i: functions/PRML/src/PRMLSVM.cpp.i

.PHONY : functions/PRML/src/PRMLSVM.i

# target to preprocess a source file
functions/PRML/src/PRMLSVM.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/PRML/src/PRMLSVM.cpp.i
.PHONY : functions/PRML/src/PRMLSVM.cpp.i

functions/PRML/src/PRMLSVM.s: functions/PRML/src/PRMLSVM.cpp.s

.PHONY : functions/PRML/src/PRMLSVM.s

# target to generate assembly for a file
functions/PRML/src/PRMLSVM.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/PRML/src/PRMLSVM.cpp.s
.PHONY : functions/PRML/src/PRMLSVM.cpp.s

functions/PRVerify/src/PRVerify.o: functions/PRVerify/src/PRVerify.cpp.o

.PHONY : functions/PRVerify/src/PRVerify.o

# target to build an object file
functions/PRVerify/src/PRVerify.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/PRVerify/src/PRVerify.cpp.o
.PHONY : functions/PRVerify/src/PRVerify.cpp.o

functions/PRVerify/src/PRVerify.i: functions/PRVerify/src/PRVerify.cpp.i

.PHONY : functions/PRVerify/src/PRVerify.i

# target to preprocess a source file
functions/PRVerify/src/PRVerify.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/PRVerify/src/PRVerify.cpp.i
.PHONY : functions/PRVerify/src/PRVerify.cpp.i

functions/PRVerify/src/PRVerify.s: functions/PRVerify/src/PRVerify.cpp.s

.PHONY : functions/PRVerify/src/PRVerify.s

# target to generate assembly for a file
functions/PRVerify/src/PRVerify.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/PRVerify/src/PRVerify.cpp.s
.PHONY : functions/PRVerify/src/PRVerify.cpp.s

functions/extract_features/features_base.o: functions/extract_features/features_base.cpp.o

.PHONY : functions/extract_features/features_base.o

# target to build an object file
functions/extract_features/features_base.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_features/features_base.cpp.o
.PHONY : functions/extract_features/features_base.cpp.o

functions/extract_features/features_base.i: functions/extract_features/features_base.cpp.i

.PHONY : functions/extract_features/features_base.i

# target to preprocess a source file
functions/extract_features/features_base.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_features/features_base.cpp.i
.PHONY : functions/extract_features/features_base.cpp.i

functions/extract_features/features_base.s: functions/extract_features/features_base.cpp.s

.PHONY : functions/extract_features/features_base.s

# target to generate assembly for a file
functions/extract_features/features_base.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_features/features_base.cpp.s
.PHONY : functions/extract_features/features_base.cpp.s

functions/extract_features/features_coding/BDRCC.o: functions/extract_features/features_coding/BDRCC.cpp.o

.PHONY : functions/extract_features/features_coding/BDRCC.o

# target to build an object file
functions/extract_features/features_coding/BDRCC.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_features/features_coding/BDRCC.cpp.o
.PHONY : functions/extract_features/features_coding/BDRCC.cpp.o

functions/extract_features/features_coding/BDRCC.i: functions/extract_features/features_coding/BDRCC.cpp.i

.PHONY : functions/extract_features/features_coding/BDRCC.i

# target to preprocess a source file
functions/extract_features/features_coding/BDRCC.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_features/features_coding/BDRCC.cpp.i
.PHONY : functions/extract_features/features_coding/BDRCC.cpp.i

functions/extract_features/features_coding/BDRCC.s: functions/extract_features/features_coding/BDRCC.cpp.s

.PHONY : functions/extract_features/features_coding/BDRCC.s

# target to generate assembly for a file
functions/extract_features/features_coding/BDRCC.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_features/features_coding/BDRCC.cpp.s
.PHONY : functions/extract_features/features_coding/BDRCC.cpp.s

functions/extract_features/features_coding/DRCC.o: functions/extract_features/features_coding/DRCC.cpp.o

.PHONY : functions/extract_features/features_coding/DRCC.o

# target to build an object file
functions/extract_features/features_coding/DRCC.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_features/features_coding/DRCC.cpp.o
.PHONY : functions/extract_features/features_coding/DRCC.cpp.o

functions/extract_features/features_coding/DRCC.i: functions/extract_features/features_coding/DRCC.cpp.i

.PHONY : functions/extract_features/features_coding/DRCC.i

# target to preprocess a source file
functions/extract_features/features_coding/DRCC.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_features/features_coding/DRCC.cpp.i
.PHONY : functions/extract_features/features_coding/DRCC.cpp.i

functions/extract_features/features_coding/DRCC.s: functions/extract_features/features_coding/DRCC.cpp.s

.PHONY : functions/extract_features/features_coding/DRCC.s

# target to generate assembly for a file
functions/extract_features/features_coding/DRCC.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_features/features_coding/DRCC.cpp.s
.PHONY : functions/extract_features/features_coding/DRCC.cpp.s

functions/extract_features/features_coding/extract_features_with_coding.o: functions/extract_features/features_coding/extract_features_with_coding.cpp.o

.PHONY : functions/extract_features/features_coding/extract_features_with_coding.o

# target to build an object file
functions/extract_features/features_coding/extract_features_with_coding.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_features/features_coding/extract_features_with_coding.cpp.o
.PHONY : functions/extract_features/features_coding/extract_features_with_coding.cpp.o

functions/extract_features/features_coding/extract_features_with_coding.i: functions/extract_features/features_coding/extract_features_with_coding.cpp.i

.PHONY : functions/extract_features/features_coding/extract_features_with_coding.i

# target to preprocess a source file
functions/extract_features/features_coding/extract_features_with_coding.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_features/features_coding/extract_features_with_coding.cpp.i
.PHONY : functions/extract_features/features_coding/extract_features_with_coding.cpp.i

functions/extract_features/features_coding/extract_features_with_coding.s: functions/extract_features/features_coding/extract_features_with_coding.cpp.s

.PHONY : functions/extract_features/features_coding/extract_features_with_coding.s

# target to generate assembly for a file
functions/extract_features/features_coding/extract_features_with_coding.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_features/features_coding/extract_features_with_coding.cpp.s
.PHONY : functions/extract_features/features_coding/extract_features_with_coding.cpp.s

functions/extract_features/features_statistic/extract_features_with_statisic.o: functions/extract_features/features_statistic/extract_features_with_statisic.cpp.o

.PHONY : functions/extract_features/features_statistic/extract_features_with_statisic.o

# target to build an object file
functions/extract_features/features_statistic/extract_features_with_statisic.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_features/features_statistic/extract_features_with_statisic.cpp.o
.PHONY : functions/extract_features/features_statistic/extract_features_with_statisic.cpp.o

functions/extract_features/features_statistic/extract_features_with_statisic.i: functions/extract_features/features_statistic/extract_features_with_statisic.cpp.i

.PHONY : functions/extract_features/features_statistic/extract_features_with_statisic.i

# target to preprocess a source file
functions/extract_features/features_statistic/extract_features_with_statisic.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_features/features_statistic/extract_features_with_statisic.cpp.i
.PHONY : functions/extract_features/features_statistic/extract_features_with_statisic.cpp.i

functions/extract_features/features_statistic/extract_features_with_statisic.s: functions/extract_features/features_statistic/extract_features_with_statisic.cpp.s

.PHONY : functions/extract_features/features_statistic/extract_features_with_statisic.s

# target to generate assembly for a file
functions/extract_features/features_statistic/extract_features_with_statisic.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_features/features_statistic/extract_features_with_statisic.cpp.s
.PHONY : functions/extract_features/features_statistic/extract_features_with_statisic.cpp.s

functions/extract_features/features_subspace/extract_features_with_subspace.o: functions/extract_features/features_subspace/extract_features_with_subspace.cpp.o

.PHONY : functions/extract_features/features_subspace/extract_features_with_subspace.o

# target to build an object file
functions/extract_features/features_subspace/extract_features_with_subspace.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_features/features_subspace/extract_features_with_subspace.cpp.o
.PHONY : functions/extract_features/features_subspace/extract_features_with_subspace.cpp.o

functions/extract_features/features_subspace/extract_features_with_subspace.i: functions/extract_features/features_subspace/extract_features_with_subspace.cpp.i

.PHONY : functions/extract_features/features_subspace/extract_features_with_subspace.i

# target to preprocess a source file
functions/extract_features/features_subspace/extract_features_with_subspace.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_features/features_subspace/extract_features_with_subspace.cpp.i
.PHONY : functions/extract_features/features_subspace/extract_features_with_subspace.cpp.i

functions/extract_features/features_subspace/extract_features_with_subspace.s: functions/extract_features/features_subspace/extract_features_with_subspace.cpp.s

.PHONY : functions/extract_features/features_subspace/extract_features_with_subspace.s

# target to generate assembly for a file
functions/extract_features/features_subspace/extract_features_with_subspace.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_features/features_subspace/extract_features_with_subspace.cpp.s
.PHONY : functions/extract_features/features_subspace/extract_features_with_subspace.cpp.s

functions/extract_features/image_enhance/image_enhance.o: functions/extract_features/image_enhance/image_enhance.cpp.o

.PHONY : functions/extract_features/image_enhance/image_enhance.o

# target to build an object file
functions/extract_features/image_enhance/image_enhance.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_features/image_enhance/image_enhance.cpp.o
.PHONY : functions/extract_features/image_enhance/image_enhance.cpp.o

functions/extract_features/image_enhance/image_enhance.i: functions/extract_features/image_enhance/image_enhance.cpp.i

.PHONY : functions/extract_features/image_enhance/image_enhance.i

# target to preprocess a source file
functions/extract_features/image_enhance/image_enhance.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_features/image_enhance/image_enhance.cpp.i
.PHONY : functions/extract_features/image_enhance/image_enhance.cpp.i

functions/extract_features/image_enhance/image_enhance.s: functions/extract_features/image_enhance/image_enhance.cpp.s

.PHONY : functions/extract_features/image_enhance/image_enhance.s

# target to generate assembly for a file
functions/extract_features/image_enhance/image_enhance.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_features/image_enhance/image_enhance.cpp.s
.PHONY : functions/extract_features/image_enhance/image_enhance.cpp.s

functions/extract_features/image_reduce_dimension/pca.o: functions/extract_features/image_reduce_dimension/pca.cpp.o

.PHONY : functions/extract_features/image_reduce_dimension/pca.o

# target to build an object file
functions/extract_features/image_reduce_dimension/pca.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_features/image_reduce_dimension/pca.cpp.o
.PHONY : functions/extract_features/image_reduce_dimension/pca.cpp.o

functions/extract_features/image_reduce_dimension/pca.i: functions/extract_features/image_reduce_dimension/pca.cpp.i

.PHONY : functions/extract_features/image_reduce_dimension/pca.i

# target to preprocess a source file
functions/extract_features/image_reduce_dimension/pca.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_features/image_reduce_dimension/pca.cpp.i
.PHONY : functions/extract_features/image_reduce_dimension/pca.cpp.i

functions/extract_features/image_reduce_dimension/pca.s: functions/extract_features/image_reduce_dimension/pca.cpp.s

.PHONY : functions/extract_features/image_reduce_dimension/pca.s

# target to generate assembly for a file
functions/extract_features/image_reduce_dimension/pca.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_features/image_reduce_dimension/pca.cpp.s
.PHONY : functions/extract_features/image_reduce_dimension/pca.cpp.s

functions/extract_features/image_transform/dft.o: functions/extract_features/image_transform/dft.cpp.o

.PHONY : functions/extract_features/image_transform/dft.o

# target to build an object file
functions/extract_features/image_transform/dft.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_features/image_transform/dft.cpp.o
.PHONY : functions/extract_features/image_transform/dft.cpp.o

functions/extract_features/image_transform/dft.i: functions/extract_features/image_transform/dft.cpp.i

.PHONY : functions/extract_features/image_transform/dft.i

# target to preprocess a source file
functions/extract_features/image_transform/dft.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_features/image_transform/dft.cpp.i
.PHONY : functions/extract_features/image_transform/dft.cpp.i

functions/extract_features/image_transform/dft.s: functions/extract_features/image_transform/dft.cpp.s

.PHONY : functions/extract_features/image_transform/dft.s

# target to generate assembly for a file
functions/extract_features/image_transform/dft.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_features/image_transform/dft.cpp.s
.PHONY : functions/extract_features/image_transform/dft.cpp.s

functions/extract_features/image_transform/gabor.o: functions/extract_features/image_transform/gabor.cpp.o

.PHONY : functions/extract_features/image_transform/gabor.o

# target to build an object file
functions/extract_features/image_transform/gabor.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_features/image_transform/gabor.cpp.o
.PHONY : functions/extract_features/image_transform/gabor.cpp.o

functions/extract_features/image_transform/gabor.i: functions/extract_features/image_transform/gabor.cpp.i

.PHONY : functions/extract_features/image_transform/gabor.i

# target to preprocess a source file
functions/extract_features/image_transform/gabor.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_features/image_transform/gabor.cpp.i
.PHONY : functions/extract_features/image_transform/gabor.cpp.i

functions/extract_features/image_transform/gabor.s: functions/extract_features/image_transform/gabor.cpp.s

.PHONY : functions/extract_features/image_transform/gabor.s

# target to generate assembly for a file
functions/extract_features/image_transform/gabor.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_features/image_transform/gabor.cpp.s
.PHONY : functions/extract_features/image_transform/gabor.cpp.s

functions/extract_features/image_transform/wavelet.o: functions/extract_features/image_transform/wavelet.cpp.o

.PHONY : functions/extract_features/image_transform/wavelet.o

# target to build an object file
functions/extract_features/image_transform/wavelet.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_features/image_transform/wavelet.cpp.o
.PHONY : functions/extract_features/image_transform/wavelet.cpp.o

functions/extract_features/image_transform/wavelet.i: functions/extract_features/image_transform/wavelet.cpp.i

.PHONY : functions/extract_features/image_transform/wavelet.i

# target to preprocess a source file
functions/extract_features/image_transform/wavelet.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_features/image_transform/wavelet.cpp.i
.PHONY : functions/extract_features/image_transform/wavelet.cpp.i

functions/extract_features/image_transform/wavelet.s: functions/extract_features/image_transform/wavelet.cpp.s

.PHONY : functions/extract_features/image_transform/wavelet.s

# target to generate assembly for a file
functions/extract_features/image_transform/wavelet.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_features/image_transform/wavelet.cpp.s
.PHONY : functions/extract_features/image_transform/wavelet.cpp.s

functions/extract_roi/extract_roi.o: functions/extract_roi/extract_roi.cpp.o

.PHONY : functions/extract_roi/extract_roi.o

# target to build an object file
functions/extract_roi/extract_roi.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_roi/extract_roi.cpp.o
.PHONY : functions/extract_roi/extract_roi.cpp.o

functions/extract_roi/extract_roi.i: functions/extract_roi/extract_roi.cpp.i

.PHONY : functions/extract_roi/extract_roi.i

# target to preprocess a source file
functions/extract_roi/extract_roi.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_roi/extract_roi.cpp.i
.PHONY : functions/extract_roi/extract_roi.cpp.i

functions/extract_roi/extract_roi.s: functions/extract_roi/extract_roi.cpp.s

.PHONY : functions/extract_roi/extract_roi.s

# target to generate assembly for a file
functions/extract_roi/extract_roi.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_roi/extract_roi.cpp.s
.PHONY : functions/extract_roi/extract_roi.cpp.s

functions/extract_roi/peak_valley_detect.o: functions/extract_roi/peak_valley_detect.cpp.o

.PHONY : functions/extract_roi/peak_valley_detect.o

# target to build an object file
functions/extract_roi/peak_valley_detect.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_roi/peak_valley_detect.cpp.o
.PHONY : functions/extract_roi/peak_valley_detect.cpp.o

functions/extract_roi/peak_valley_detect.i: functions/extract_roi/peak_valley_detect.cpp.i

.PHONY : functions/extract_roi/peak_valley_detect.i

# target to preprocess a source file
functions/extract_roi/peak_valley_detect.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_roi/peak_valley_detect.cpp.i
.PHONY : functions/extract_roi/peak_valley_detect.cpp.i

functions/extract_roi/peak_valley_detect.s: functions/extract_roi/peak_valley_detect.cpp.s

.PHONY : functions/extract_roi/peak_valley_detect.s

# target to generate assembly for a file
functions/extract_roi/peak_valley_detect.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/extract_roi/peak_valley_detect.cpp.s
.PHONY : functions/extract_roi/peak_valley_detect.cpp.s

functions/pretreatment/adjust_palm.o: functions/pretreatment/adjust_palm.cpp.o

.PHONY : functions/pretreatment/adjust_palm.o

# target to build an object file
functions/pretreatment/adjust_palm.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/pretreatment/adjust_palm.cpp.o
.PHONY : functions/pretreatment/adjust_palm.cpp.o

functions/pretreatment/adjust_palm.i: functions/pretreatment/adjust_palm.cpp.i

.PHONY : functions/pretreatment/adjust_palm.i

# target to preprocess a source file
functions/pretreatment/adjust_palm.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/pretreatment/adjust_palm.cpp.i
.PHONY : functions/pretreatment/adjust_palm.cpp.i

functions/pretreatment/adjust_palm.s: functions/pretreatment/adjust_palm.cpp.s

.PHONY : functions/pretreatment/adjust_palm.s

# target to generate assembly for a file
functions/pretreatment/adjust_palm.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/pretreatment/adjust_palm.cpp.s
.PHONY : functions/pretreatment/adjust_palm.cpp.s

functions/pretreatment/binarization.o: functions/pretreatment/binarization.cpp.o

.PHONY : functions/pretreatment/binarization.o

# target to build an object file
functions/pretreatment/binarization.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/pretreatment/binarization.cpp.o
.PHONY : functions/pretreatment/binarization.cpp.o

functions/pretreatment/binarization.i: functions/pretreatment/binarization.cpp.i

.PHONY : functions/pretreatment/binarization.i

# target to preprocess a source file
functions/pretreatment/binarization.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/pretreatment/binarization.cpp.i
.PHONY : functions/pretreatment/binarization.cpp.i

functions/pretreatment/binarization.s: functions/pretreatment/binarization.cpp.s

.PHONY : functions/pretreatment/binarization.s

# target to generate assembly for a file
functions/pretreatment/binarization.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/pretreatment/binarization.cpp.s
.PHONY : functions/pretreatment/binarization.cpp.s

functions/process_parameter/process_parameter.o: functions/process_parameter/process_parameter.cpp.o

.PHONY : functions/process_parameter/process_parameter.o

# target to build an object file
functions/process_parameter/process_parameter.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/process_parameter/process_parameter.cpp.o
.PHONY : functions/process_parameter/process_parameter.cpp.o

functions/process_parameter/process_parameter.i: functions/process_parameter/process_parameter.cpp.i

.PHONY : functions/process_parameter/process_parameter.i

# target to preprocess a source file
functions/process_parameter/process_parameter.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/process_parameter/process_parameter.cpp.i
.PHONY : functions/process_parameter/process_parameter.cpp.i

functions/process_parameter/process_parameter.s: functions/process_parameter/process_parameter.cpp.s

.PHONY : functions/process_parameter/process_parameter.s

# target to generate assembly for a file
functions/process_parameter/process_parameter.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/process_parameter/process_parameter.cpp.s
.PHONY : functions/process_parameter/process_parameter.cpp.s

global/general_function.o: global/general_function.cpp.o

.PHONY : global/general_function.o

# target to build an object file
global/general_function.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/global/general_function.cpp.o
.PHONY : global/general_function.cpp.o

global/general_function.i: global/general_function.cpp.i

.PHONY : global/general_function.i

# target to preprocess a source file
global/general_function.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/global/general_function.cpp.i
.PHONY : global/general_function.cpp.i

global/general_function.s: global/general_function.cpp.s

.PHONY : global/general_function.s

# target to generate assembly for a file
global/general_function.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/global/general_function.cpp.s
.PHONY : global/general_function.cpp.s

global/general_functions.o: global/general_functions.cpp.o

.PHONY : global/general_functions.o

# target to build an object file
global/general_functions.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/global/general_functions.cpp.o
.PHONY : global/general_functions.cpp.o

global/general_functions.i: global/general_functions.cpp.i

.PHONY : global/general_functions.i

# target to preprocess a source file
global/general_functions.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/global/general_functions.cpp.i
.PHONY : global/general_functions.cpp.i

global/general_functions.s: global/general_functions.cpp.s

.PHONY : global/general_functions.s

# target to generate assembly for a file
global/general_functions.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/global/general_functions.cpp.s
.PHONY : global/general_functions.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... main"
	@echo "... functions/PRML/src/PRML.o"
	@echo "... functions/PRML/src/PRML.i"
	@echo "... functions/PRML/src/PRML.s"
	@echo "... functions/PRML/src/PRMLEDRCC.o"
	@echo "... functions/PRML/src/PRMLEDRCC.i"
	@echo "... functions/PRML/src/PRMLEDRCC.s"
	@echo "... functions/PRML/src/PRMLKNearest.o"
	@echo "... functions/PRML/src/PRMLKNearest.i"
	@echo "... functions/PRML/src/PRMLKNearest.s"
	@echo "... functions/PRML/src/PRMLNBayes.o"
	@echo "... functions/PRML/src/PRMLNBayes.i"
	@echo "... functions/PRML/src/PRMLNBayes.s"
	@echo "... functions/PRML/src/PRMLSVM.o"
	@echo "... functions/PRML/src/PRMLSVM.i"
	@echo "... functions/PRML/src/PRMLSVM.s"
	@echo "... functions/PRVerify/src/PRVerify.o"
	@echo "... functions/PRVerify/src/PRVerify.i"
	@echo "... functions/PRVerify/src/PRVerify.s"
	@echo "... functions/extract_features/features_base.o"
	@echo "... functions/extract_features/features_base.i"
	@echo "... functions/extract_features/features_base.s"
	@echo "... functions/extract_features/features_coding/BDRCC.o"
	@echo "... functions/extract_features/features_coding/BDRCC.i"
	@echo "... functions/extract_features/features_coding/BDRCC.s"
	@echo "... functions/extract_features/features_coding/DRCC.o"
	@echo "... functions/extract_features/features_coding/DRCC.i"
	@echo "... functions/extract_features/features_coding/DRCC.s"
	@echo "... functions/extract_features/features_coding/extract_features_with_coding.o"
	@echo "... functions/extract_features/features_coding/extract_features_with_coding.i"
	@echo "... functions/extract_features/features_coding/extract_features_with_coding.s"
	@echo "... functions/extract_features/features_statistic/extract_features_with_statisic.o"
	@echo "... functions/extract_features/features_statistic/extract_features_with_statisic.i"
	@echo "... functions/extract_features/features_statistic/extract_features_with_statisic.s"
	@echo "... functions/extract_features/features_subspace/extract_features_with_subspace.o"
	@echo "... functions/extract_features/features_subspace/extract_features_with_subspace.i"
	@echo "... functions/extract_features/features_subspace/extract_features_with_subspace.s"
	@echo "... functions/extract_features/image_enhance/image_enhance.o"
	@echo "... functions/extract_features/image_enhance/image_enhance.i"
	@echo "... functions/extract_features/image_enhance/image_enhance.s"
	@echo "... functions/extract_features/image_reduce_dimension/pca.o"
	@echo "... functions/extract_features/image_reduce_dimension/pca.i"
	@echo "... functions/extract_features/image_reduce_dimension/pca.s"
	@echo "... functions/extract_features/image_transform/dft.o"
	@echo "... functions/extract_features/image_transform/dft.i"
	@echo "... functions/extract_features/image_transform/dft.s"
	@echo "... functions/extract_features/image_transform/gabor.o"
	@echo "... functions/extract_features/image_transform/gabor.i"
	@echo "... functions/extract_features/image_transform/gabor.s"
	@echo "... functions/extract_features/image_transform/wavelet.o"
	@echo "... functions/extract_features/image_transform/wavelet.i"
	@echo "... functions/extract_features/image_transform/wavelet.s"
	@echo "... functions/extract_roi/extract_roi.o"
	@echo "... functions/extract_roi/extract_roi.i"
	@echo "... functions/extract_roi/extract_roi.s"
	@echo "... functions/extract_roi/peak_valley_detect.o"
	@echo "... functions/extract_roi/peak_valley_detect.i"
	@echo "... functions/extract_roi/peak_valley_detect.s"
	@echo "... functions/pretreatment/adjust_palm.o"
	@echo "... functions/pretreatment/adjust_palm.i"
	@echo "... functions/pretreatment/adjust_palm.s"
	@echo "... functions/pretreatment/binarization.o"
	@echo "... functions/pretreatment/binarization.i"
	@echo "... functions/pretreatment/binarization.s"
	@echo "... functions/process_parameter/process_parameter.o"
	@echo "... functions/process_parameter/process_parameter.i"
	@echo "... functions/process_parameter/process_parameter.s"
	@echo "... global/general_function.o"
	@echo "... global/general_function.i"
	@echo "... global/general_function.s"
	@echo "... global/general_functions.o"
	@echo "... global/general_functions.i"
	@echo "... global/general_functions.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

